namespace LushMed
{
    partial class admin_sales
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(admin_sales));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelsbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.servicesbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.salesbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.usersbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Logout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuGradientPanel2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.BorderRadius = 1;
            this.bunifuGradientPanel2.Controls.Add(this.bunifuButton1);
            this.bunifuGradientPanel2.Controls.Add(this.panelsbtn);
            this.bunifuGradientPanel2.Controls.Add(this.servicesbtn);
            this.bunifuGradientPanel2.Controls.Add(this.salesbtn);
            this.bunifuGradientPanel2.Controls.Add(this.usersbtn);
            this.bunifuGradientPanel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(146)))), ((int)(((byte)(90)))));
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(146)))), ((int)(((byte)(90)))));
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(0, 101);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(218, 699);
            this.bunifuGradientPanel2.TabIndex = 4;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Record";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IconLeft")));
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(0, 320);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 0;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 0;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.onHoverState.BorderRadius = 0;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 0;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.OnIdleState.BorderRadius = 0;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 0;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.OnPressedState.BorderRadius = 0;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 0;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(218, 58);
            this.bunifuButton1.TabIndex = 4;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // panelsbtn
            // 
            this.panelsbtn.AllowAnimations = true;
            this.panelsbtn.AllowMouseEffects = true;
            this.panelsbtn.AllowToggling = false;
            this.panelsbtn.AnimationSpeed = 200;
            this.panelsbtn.AutoGenerateColors = false;
            this.panelsbtn.AutoRoundBorders = false;
            this.panelsbtn.AutoSizeLeftIcon = true;
            this.panelsbtn.AutoSizeRightIcon = true;
            this.panelsbtn.BackColor = System.Drawing.Color.Transparent;
            this.panelsbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.panelsbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelsbtn.BackgroundImage")));
            this.panelsbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.panelsbtn.ButtonText = "Panels";
            this.panelsbtn.ButtonTextMarginLeft = 0;
            this.panelsbtn.ColorContrastOnClick = 45;
            this.panelsbtn.ColorContrastOnHover = 45;
            this.panelsbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.panelsbtn.CustomizableEdges = borderEdges2;
            this.panelsbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.panelsbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.panelsbtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.panelsbtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.panelsbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.panelsbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.panelsbtn.ForeColor = System.Drawing.Color.Black;
            this.panelsbtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("panelsbtn.IconLeft")));
            this.panelsbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.panelsbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.panelsbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.panelsbtn.IconMarginLeft = 11;
            this.panelsbtn.IconPadding = 10;
            this.panelsbtn.IconRight = null;
            this.panelsbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.panelsbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.panelsbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.panelsbtn.IconSize = 25;
            this.panelsbtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.panelsbtn.IdleBorderRadius = 0;
            this.panelsbtn.IdleBorderThickness = 0;
            this.panelsbtn.IdleFillColor = System.Drawing.Color.Empty;
            this.panelsbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("panelsbtn.IdleIconLeftImage")));
            this.panelsbtn.IdleIconRightImage = null;
            this.panelsbtn.IndicateFocus = false;
            this.panelsbtn.Location = new System.Drawing.Point(0, 265);
            this.panelsbtn.Name = "panelsbtn";
            this.panelsbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.panelsbtn.OnDisabledState.BorderRadius = 0;
            this.panelsbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.panelsbtn.OnDisabledState.BorderThickness = 0;
            this.panelsbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.panelsbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.panelsbtn.OnDisabledState.IconLeftImage = null;
            this.panelsbtn.OnDisabledState.IconRightImage = null;
            this.panelsbtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.panelsbtn.onHoverState.BorderRadius = 0;
            this.panelsbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.panelsbtn.onHoverState.BorderThickness = 0;
            this.panelsbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.panelsbtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.panelsbtn.onHoverState.IconLeftImage = null;
            this.panelsbtn.onHoverState.IconRightImage = null;
            this.panelsbtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.panelsbtn.OnIdleState.BorderRadius = 0;
            this.panelsbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.panelsbtn.OnIdleState.BorderThickness = 0;
            this.panelsbtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.panelsbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.panelsbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("panelsbtn.OnIdleState.IconLeftImage")));
            this.panelsbtn.OnIdleState.IconRightImage = null;
            this.panelsbtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.panelsbtn.OnPressedState.BorderRadius = 0;
            this.panelsbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.panelsbtn.OnPressedState.BorderThickness = 0;
            this.panelsbtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.panelsbtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.panelsbtn.OnPressedState.IconLeftImage = null;
            this.panelsbtn.OnPressedState.IconRightImage = null;
            this.panelsbtn.Size = new System.Drawing.Size(218, 58);
            this.panelsbtn.TabIndex = 3;
            this.panelsbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.panelsbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.panelsbtn.TextMarginLeft = 0;
            this.panelsbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.panelsbtn.UseDefaultRadiusAndThickness = true;
            this.panelsbtn.Click += new System.EventHandler(this.panelsbtn_Click);
            // 
            // servicesbtn
            // 
            this.servicesbtn.AllowAnimations = true;
            this.servicesbtn.AllowMouseEffects = true;
            this.servicesbtn.AllowToggling = false;
            this.servicesbtn.AnimationSpeed = 200;
            this.servicesbtn.AutoGenerateColors = false;
            this.servicesbtn.AutoRoundBorders = false;
            this.servicesbtn.AutoSizeLeftIcon = true;
            this.servicesbtn.AutoSizeRightIcon = true;
            this.servicesbtn.BackColor = System.Drawing.Color.Transparent;
            this.servicesbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.servicesbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("servicesbtn.BackgroundImage")));
            this.servicesbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.servicesbtn.ButtonText = "Services";
            this.servicesbtn.ButtonTextMarginLeft = 0;
            this.servicesbtn.ColorContrastOnClick = 45;
            this.servicesbtn.ColorContrastOnHover = 45;
            this.servicesbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.servicesbtn.CustomizableEdges = borderEdges3;
            this.servicesbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.servicesbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.servicesbtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.servicesbtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.servicesbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.servicesbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.servicesbtn.ForeColor = System.Drawing.Color.Black;
            this.servicesbtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("servicesbtn.IconLeft")));
            this.servicesbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.servicesbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.servicesbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.servicesbtn.IconMarginLeft = 11;
            this.servicesbtn.IconPadding = 10;
            this.servicesbtn.IconRight = null;
            this.servicesbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.servicesbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.servicesbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.servicesbtn.IconSize = 25;
            this.servicesbtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.servicesbtn.IdleBorderRadius = 0;
            this.servicesbtn.IdleBorderThickness = 0;
            this.servicesbtn.IdleFillColor = System.Drawing.Color.Empty;
            this.servicesbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("servicesbtn.IdleIconLeftImage")));
            this.servicesbtn.IdleIconRightImage = null;
            this.servicesbtn.IndicateFocus = false;
            this.servicesbtn.Location = new System.Drawing.Point(0, 208);
            this.servicesbtn.Name = "servicesbtn";
            this.servicesbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.servicesbtn.OnDisabledState.BorderRadius = 0;
            this.servicesbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.servicesbtn.OnDisabledState.BorderThickness = 0;
            this.servicesbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.servicesbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.servicesbtn.OnDisabledState.IconLeftImage = null;
            this.servicesbtn.OnDisabledState.IconRightImage = null;
            this.servicesbtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.servicesbtn.onHoverState.BorderRadius = 0;
            this.servicesbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.servicesbtn.onHoverState.BorderThickness = 0;
            this.servicesbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.servicesbtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.servicesbtn.onHoverState.IconLeftImage = null;
            this.servicesbtn.onHoverState.IconRightImage = null;
            this.servicesbtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.servicesbtn.OnIdleState.BorderRadius = 0;
            this.servicesbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.servicesbtn.OnIdleState.BorderThickness = 0;
            this.servicesbtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.servicesbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.servicesbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("servicesbtn.OnIdleState.IconLeftImage")));
            this.servicesbtn.OnIdleState.IconRightImage = null;
            this.servicesbtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.servicesbtn.OnPressedState.BorderRadius = 0;
            this.servicesbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.servicesbtn.OnPressedState.BorderThickness = 0;
            this.servicesbtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.servicesbtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.servicesbtn.OnPressedState.IconLeftImage = null;
            this.servicesbtn.OnPressedState.IconRightImage = null;
            this.servicesbtn.Size = new System.Drawing.Size(218, 58);
            this.servicesbtn.TabIndex = 2;
            this.servicesbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.servicesbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.servicesbtn.TextMarginLeft = 0;
            this.servicesbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.servicesbtn.UseDefaultRadiusAndThickness = true;
            this.servicesbtn.Click += new System.EventHandler(this.servicesbtn_Click);
            // 
            // salesbtn
            // 
            this.salesbtn.AllowAnimations = true;
            this.salesbtn.AllowMouseEffects = true;
            this.salesbtn.AllowToggling = false;
            this.salesbtn.AnimationSpeed = 200;
            this.salesbtn.AutoGenerateColors = false;
            this.salesbtn.AutoRoundBorders = false;
            this.salesbtn.AutoSizeLeftIcon = true;
            this.salesbtn.AutoSizeRightIcon = true;
            this.salesbtn.BackColor = System.Drawing.Color.Transparent;
            this.salesbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.salesbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("salesbtn.BackgroundImage")));
            this.salesbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salesbtn.ButtonText = "Sales";
            this.salesbtn.ButtonTextMarginLeft = 0;
            this.salesbtn.ColorContrastOnClick = 45;
            this.salesbtn.ColorContrastOnHover = 45;
            this.salesbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.salesbtn.CustomizableEdges = borderEdges4;
            this.salesbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.salesbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.salesbtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.salesbtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.salesbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.salesbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.salesbtn.ForeColor = System.Drawing.Color.Black;
            this.salesbtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("salesbtn.IconLeft")));
            this.salesbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.salesbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.salesbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.salesbtn.IconMarginLeft = 11;
            this.salesbtn.IconPadding = 10;
            this.salesbtn.IconRight = null;
            this.salesbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.salesbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.salesbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.salesbtn.IconSize = 25;
            this.salesbtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.salesbtn.IdleBorderRadius = 0;
            this.salesbtn.IdleBorderThickness = 0;
            this.salesbtn.IdleFillColor = System.Drawing.Color.Empty;
            this.salesbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("salesbtn.IdleIconLeftImage")));
            this.salesbtn.IdleIconRightImage = null;
            this.salesbtn.IndicateFocus = false;
            this.salesbtn.Location = new System.Drawing.Point(12, 151);
            this.salesbtn.Name = "salesbtn";
            this.salesbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.salesbtn.OnDisabledState.BorderRadius = 0;
            this.salesbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salesbtn.OnDisabledState.BorderThickness = 0;
            this.salesbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.salesbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.salesbtn.OnDisabledState.IconLeftImage = null;
            this.salesbtn.OnDisabledState.IconRightImage = null;
            this.salesbtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.salesbtn.onHoverState.BorderRadius = 0;
            this.salesbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salesbtn.onHoverState.BorderThickness = 0;
            this.salesbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.salesbtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.salesbtn.onHoverState.IconLeftImage = null;
            this.salesbtn.onHoverState.IconRightImage = null;
            this.salesbtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.salesbtn.OnIdleState.BorderRadius = 0;
            this.salesbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salesbtn.OnIdleState.BorderThickness = 0;
            this.salesbtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.salesbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.salesbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("salesbtn.OnIdleState.IconLeftImage")));
            this.salesbtn.OnIdleState.IconRightImage = null;
            this.salesbtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.salesbtn.OnPressedState.BorderRadius = 0;
            this.salesbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salesbtn.OnPressedState.BorderThickness = 0;
            this.salesbtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.salesbtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.salesbtn.OnPressedState.IconLeftImage = null;
            this.salesbtn.OnPressedState.IconRightImage = null;
            this.salesbtn.Size = new System.Drawing.Size(206, 58);
            this.salesbtn.TabIndex = 1;
            this.salesbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.salesbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.salesbtn.TextMarginLeft = 0;
            this.salesbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.salesbtn.UseDefaultRadiusAndThickness = true;
            this.salesbtn.Click += new System.EventHandler(this.salesbtn_Click);
            // 
            // usersbtn
            // 
            this.usersbtn.AllowAnimations = true;
            this.usersbtn.AllowMouseEffects = true;
            this.usersbtn.AllowToggling = false;
            this.usersbtn.AnimationSpeed = 200;
            this.usersbtn.AutoGenerateColors = false;
            this.usersbtn.AutoRoundBorders = false;
            this.usersbtn.AutoSizeLeftIcon = true;
            this.usersbtn.AutoSizeRightIcon = true;
            this.usersbtn.BackColor = System.Drawing.Color.Transparent;
            this.usersbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.usersbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usersbtn.BackgroundImage")));
            this.usersbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usersbtn.ButtonText = "Users";
            this.usersbtn.ButtonTextMarginLeft = 0;
            this.usersbtn.ColorContrastOnClick = 45;
            this.usersbtn.ColorContrastOnHover = 45;
            this.usersbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.usersbtn.CustomizableEdges = borderEdges5;
            this.usersbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.usersbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.usersbtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.usersbtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.usersbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.usersbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.usersbtn.ForeColor = System.Drawing.Color.Black;
            this.usersbtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("usersbtn.IconLeft")));
            this.usersbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.usersbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.usersbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.usersbtn.IconMarginLeft = 11;
            this.usersbtn.IconPadding = 10;
            this.usersbtn.IconRight = null;
            this.usersbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.usersbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.usersbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.usersbtn.IconSize = 25;
            this.usersbtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.usersbtn.IdleBorderRadius = 0;
            this.usersbtn.IdleBorderThickness = 0;
            this.usersbtn.IdleFillColor = System.Drawing.Color.Empty;
            this.usersbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("usersbtn.IdleIconLeftImage")));
            this.usersbtn.IdleIconRightImage = null;
            this.usersbtn.IndicateFocus = false;
            this.usersbtn.Location = new System.Drawing.Point(0, 94);
            this.usersbtn.Name = "usersbtn";
            this.usersbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.usersbtn.OnDisabledState.BorderRadius = 0;
            this.usersbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usersbtn.OnDisabledState.BorderThickness = 0;
            this.usersbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.usersbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.usersbtn.OnDisabledState.IconLeftImage = null;
            this.usersbtn.OnDisabledState.IconRightImage = null;
            this.usersbtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.usersbtn.onHoverState.BorderRadius = 0;
            this.usersbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usersbtn.onHoverState.BorderThickness = 0;
            this.usersbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.usersbtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.usersbtn.onHoverState.IconLeftImage = null;
            this.usersbtn.onHoverState.IconRightImage = null;
            this.usersbtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.usersbtn.OnIdleState.BorderRadius = 0;
            this.usersbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usersbtn.OnIdleState.BorderThickness = 0;
            this.usersbtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.usersbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.usersbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("usersbtn.OnIdleState.IconLeftImage")));
            this.usersbtn.OnIdleState.IconRightImage = null;
            this.usersbtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.usersbtn.OnPressedState.BorderRadius = 0;
            this.usersbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usersbtn.OnPressedState.BorderThickness = 0;
            this.usersbtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.usersbtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.usersbtn.OnPressedState.IconLeftImage = null;
            this.usersbtn.OnPressedState.IconRightImage = null;
            this.usersbtn.Size = new System.Drawing.Size(218, 58);
            this.usersbtn.TabIndex = 0;
            this.usersbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.usersbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.usersbtn.TextMarginLeft = 0;
            this.usersbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.usersbtn.UseDefaultRadiusAndThickness = true;
            this.usersbtn.Click += new System.EventHandler(this.usersbtn_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.Logout);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox2);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1300, 101);
            this.bunifuPanel1.TabIndex = 3;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(1085, 62);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(29, 20);
            this.bunifuLabel1.TabIndex = 5;
            this.bunifuLabel1.Text = "Lush";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Logout
            // 
            this.Logout.AllowAnimations = true;
            this.Logout.AllowMouseEffects = true;
            this.Logout.AllowToggling = false;
            this.Logout.AnimationSpeed = 200;
            this.Logout.AutoGenerateColors = false;
            this.Logout.AutoRoundBorders = false;
            this.Logout.AutoSizeLeftIcon = true;
            this.Logout.AutoSizeRightIcon = true;
            this.Logout.BackColor = System.Drawing.Color.Transparent;
            this.Logout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Logout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Logout.BackgroundImage")));
            this.Logout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.ButtonText = "Logout";
            this.Logout.ButtonTextMarginLeft = 0;
            this.Logout.ColorContrastOnClick = 45;
            this.Logout.ColorContrastOnHover = 45;
            this.Logout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.Logout.CustomizableEdges = borderEdges6;
            this.Logout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Logout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Logout.DisabledFillColor = System.Drawing.Color.Empty;
            this.Logout.DisabledForecolor = System.Drawing.Color.Empty;
            this.Logout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Logout.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Logout.ForeColor = System.Drawing.Color.Black;
            this.Logout.IconLeft = null;
            this.Logout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Logout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Logout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Logout.IconMarginLeft = 11;
            this.Logout.IconPadding = 10;
            this.Logout.IconRight = ((System.Drawing.Image)(resources.GetObject("Logout.IconRight")));
            this.Logout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Logout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Logout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Logout.IconSize = 25;
            this.Logout.IdleBorderColor = System.Drawing.Color.Empty;
            this.Logout.IdleBorderRadius = 0;
            this.Logout.IdleBorderThickness = 0;
            this.Logout.IdleFillColor = System.Drawing.Color.Empty;
            this.Logout.IdleIconLeftImage = null;
            this.Logout.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Logout.IdleIconRightImage")));
            this.Logout.IndicateFocus = false;
            this.Logout.Location = new System.Drawing.Point(1138, 24);
            this.Logout.Name = "Logout";
            this.Logout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Logout.OnDisabledState.BorderRadius = 0;
            this.Logout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnDisabledState.BorderThickness = 0;
            this.Logout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Logout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Logout.OnDisabledState.IconLeftImage = null;
            this.Logout.OnDisabledState.IconRightImage = null;
            this.Logout.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.onHoverState.BorderRadius = 0;
            this.Logout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.onHoverState.BorderThickness = 0;
            this.Logout.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.Logout.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Logout.onHoverState.IconLeftImage = null;
            this.Logout.onHoverState.IconRightImage = null;
            this.Logout.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.OnIdleState.BorderRadius = 0;
            this.Logout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnIdleState.BorderThickness = 0;
            this.Logout.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Logout.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Logout.OnIdleState.IconLeftImage = null;
            this.Logout.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Logout.OnIdleState.IconRightImage")));
            this.Logout.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.OnPressedState.BorderRadius = 0;
            this.Logout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnPressedState.BorderThickness = 0;
            this.Logout.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Logout.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Logout.OnPressedState.IconLeftImage = null;
            this.Logout.OnPressedState.IconRightImage = null;
            this.Logout.Size = new System.Drawing.Size(146, 58);
            this.Logout.TabIndex = 6;
            this.Logout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Logout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Logout.TextMarginLeft = 0;
            this.Logout.TextPadding = new System.Windows.Forms.Padding(0);
            this.Logout.UseDefaultRadiusAndThickness = true;
            this.Logout.Click += new System.EventHandler(this.Logout_Click);
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 22;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(1078, 14);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(44, 44);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 4;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(27, -93);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(282, 282);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // admin_sales
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1300, 800);
            this.Controls.Add(this.bunifuGradientPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "admin_sales";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "admin_sales";
            this.bunifuGradientPanel2.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton panelsbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton servicesbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton salesbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton usersbtn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Logout;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}