namespace LushMed
{
    partial class user_options
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(user_options));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.optionsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.receptionbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.Logout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.profile = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.Cash = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.data_Grid = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.Cash_tally = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.FeedbackLbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.Save_pass = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.confirm_pass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.new_pass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.present_pass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Total_Sale = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.Cash.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.data_Grid)).BeginInit();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.BorderRadius = 1;
            this.bunifuGradientPanel2.Controls.Add(this.optionsBtn);
            this.bunifuGradientPanel2.Controls.Add(this.receptionbtn);
            this.bunifuGradientPanel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(146)))), ((int)(((byte)(90)))));
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(146)))), ((int)(((byte)(90)))));
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(0, 101);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(218, 699);
            this.bunifuGradientPanel2.TabIndex = 38;
            // 
            // optionsBtn
            // 
            this.optionsBtn.AllowAnimations = true;
            this.optionsBtn.AllowMouseEffects = true;
            this.optionsBtn.AllowToggling = false;
            this.optionsBtn.AnimationSpeed = 200;
            this.optionsBtn.AutoGenerateColors = false;
            this.optionsBtn.AutoRoundBorders = false;
            this.optionsBtn.AutoSizeLeftIcon = true;
            this.optionsBtn.AutoSizeRightIcon = true;
            this.optionsBtn.BackColor = System.Drawing.Color.Transparent;
            this.optionsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.optionsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("optionsBtn.BackgroundImage")));
            this.optionsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.optionsBtn.ButtonText = "Options";
            this.optionsBtn.ButtonTextMarginLeft = 0;
            this.optionsBtn.ColorContrastOnClick = 45;
            this.optionsBtn.ColorContrastOnHover = 45;
            this.optionsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.optionsBtn.CustomizableEdges = borderEdges1;
            this.optionsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.optionsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.optionsBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.optionsBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.optionsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.optionsBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.optionsBtn.ForeColor = System.Drawing.Color.Black;
            this.optionsBtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("optionsBtn.IconLeft")));
            this.optionsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.optionsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.optionsBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.optionsBtn.IconMarginLeft = 11;
            this.optionsBtn.IconPadding = 10;
            this.optionsBtn.IconRight = null;
            this.optionsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.optionsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.optionsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.optionsBtn.IconSize = 25;
            this.optionsBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.optionsBtn.IdleBorderRadius = 0;
            this.optionsBtn.IdleBorderThickness = 0;
            this.optionsBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.optionsBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("optionsBtn.IdleIconLeftImage")));
            this.optionsBtn.IdleIconRightImage = null;
            this.optionsBtn.IndicateFocus = false;
            this.optionsBtn.Location = new System.Drawing.Point(12, 151);
            this.optionsBtn.Name = "optionsBtn";
            this.optionsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.optionsBtn.OnDisabledState.BorderRadius = 0;
            this.optionsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.optionsBtn.OnDisabledState.BorderThickness = 0;
            this.optionsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.optionsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.optionsBtn.OnDisabledState.IconLeftImage = null;
            this.optionsBtn.OnDisabledState.IconRightImage = null;
            this.optionsBtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.optionsBtn.onHoverState.BorderRadius = 0;
            this.optionsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.optionsBtn.onHoverState.BorderThickness = 0;
            this.optionsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.optionsBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.optionsBtn.onHoverState.IconLeftImage = null;
            this.optionsBtn.onHoverState.IconRightImage = null;
            this.optionsBtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.optionsBtn.OnIdleState.BorderRadius = 0;
            this.optionsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.optionsBtn.OnIdleState.BorderThickness = 0;
            this.optionsBtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.optionsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.optionsBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("optionsBtn.OnIdleState.IconLeftImage")));
            this.optionsBtn.OnIdleState.IconRightImage = null;
            this.optionsBtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.optionsBtn.OnPressedState.BorderRadius = 0;
            this.optionsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.optionsBtn.OnPressedState.BorderThickness = 0;
            this.optionsBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.optionsBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.optionsBtn.OnPressedState.IconLeftImage = null;
            this.optionsBtn.OnPressedState.IconRightImage = null;
            this.optionsBtn.Size = new System.Drawing.Size(206, 58);
            this.optionsBtn.TabIndex = 1;
            this.optionsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.optionsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.optionsBtn.TextMarginLeft = 0;
            this.optionsBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.optionsBtn.UseDefaultRadiusAndThickness = true;
            this.optionsBtn.Click += new System.EventHandler(this.optionsBtn_Click);
            // 
            // receptionbtn
            // 
            this.receptionbtn.AllowAnimations = true;
            this.receptionbtn.AllowMouseEffects = true;
            this.receptionbtn.AllowToggling = false;
            this.receptionbtn.AnimationSpeed = 200;
            this.receptionbtn.AutoGenerateColors = false;
            this.receptionbtn.AutoRoundBorders = false;
            this.receptionbtn.AutoSizeLeftIcon = true;
            this.receptionbtn.AutoSizeRightIcon = true;
            this.receptionbtn.BackColor = System.Drawing.Color.Transparent;
            this.receptionbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.receptionbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("receptionbtn.BackgroundImage")));
            this.receptionbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.receptionbtn.ButtonText = "Reception";
            this.receptionbtn.ButtonTextMarginLeft = 0;
            this.receptionbtn.ColorContrastOnClick = 45;
            this.receptionbtn.ColorContrastOnHover = 45;
            this.receptionbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.receptionbtn.CustomizableEdges = borderEdges2;
            this.receptionbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.receptionbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.receptionbtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.receptionbtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.receptionbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.receptionbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.receptionbtn.ForeColor = System.Drawing.Color.Black;
            this.receptionbtn.IconLeft = ((System.Drawing.Image)(resources.GetObject("receptionbtn.IconLeft")));
            this.receptionbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.receptionbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.receptionbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.receptionbtn.IconMarginLeft = 11;
            this.receptionbtn.IconPadding = 10;
            this.receptionbtn.IconRight = null;
            this.receptionbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.receptionbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.receptionbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.receptionbtn.IconSize = 25;
            this.receptionbtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.receptionbtn.IdleBorderRadius = 0;
            this.receptionbtn.IdleBorderThickness = 0;
            this.receptionbtn.IdleFillColor = System.Drawing.Color.Empty;
            this.receptionbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("receptionbtn.IdleIconLeftImage")));
            this.receptionbtn.IdleIconRightImage = null;
            this.receptionbtn.IndicateFocus = false;
            this.receptionbtn.Location = new System.Drawing.Point(0, 94);
            this.receptionbtn.Name = "receptionbtn";
            this.receptionbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.receptionbtn.OnDisabledState.BorderRadius = 0;
            this.receptionbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.receptionbtn.OnDisabledState.BorderThickness = 0;
            this.receptionbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.receptionbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.receptionbtn.OnDisabledState.IconLeftImage = null;
            this.receptionbtn.OnDisabledState.IconRightImage = null;
            this.receptionbtn.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.receptionbtn.onHoverState.BorderRadius = 0;
            this.receptionbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.receptionbtn.onHoverState.BorderThickness = 0;
            this.receptionbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.receptionbtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.receptionbtn.onHoverState.IconLeftImage = null;
            this.receptionbtn.onHoverState.IconRightImage = null;
            this.receptionbtn.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.receptionbtn.OnIdleState.BorderRadius = 0;
            this.receptionbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.receptionbtn.OnIdleState.BorderThickness = 0;
            this.receptionbtn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.receptionbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.receptionbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("receptionbtn.OnIdleState.IconLeftImage")));
            this.receptionbtn.OnIdleState.IconRightImage = null;
            this.receptionbtn.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.receptionbtn.OnPressedState.BorderRadius = 0;
            this.receptionbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.receptionbtn.OnPressedState.BorderThickness = 0;
            this.receptionbtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.receptionbtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.receptionbtn.OnPressedState.IconLeftImage = null;
            this.receptionbtn.OnPressedState.IconRightImage = null;
            this.receptionbtn.Size = new System.Drawing.Size(218, 58);
            this.receptionbtn.TabIndex = 0;
            this.receptionbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.receptionbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.receptionbtn.TextMarginLeft = 0;
            this.receptionbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.receptionbtn.UseDefaultRadiusAndThickness = true;
            this.receptionbtn.Click += new System.EventHandler(this.receptionbtn_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.Logout);
            this.bunifuPanel1.Controls.Add(this.profile);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox2);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1300, 101);
            this.bunifuPanel1.TabIndex = 37;
            // 
            // Logout
            // 
            this.Logout.AllowAnimations = true;
            this.Logout.AllowMouseEffects = true;
            this.Logout.AllowToggling = false;
            this.Logout.AnimationSpeed = 200;
            this.Logout.AutoGenerateColors = false;
            this.Logout.AutoRoundBorders = false;
            this.Logout.AutoSizeLeftIcon = true;
            this.Logout.AutoSizeRightIcon = true;
            this.Logout.BackColor = System.Drawing.Color.Transparent;
            this.Logout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Logout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Logout.BackgroundImage")));
            this.Logout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.ButtonText = "Logout";
            this.Logout.ButtonTextMarginLeft = 0;
            this.Logout.ColorContrastOnClick = 45;
            this.Logout.ColorContrastOnHover = 45;
            this.Logout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Logout.CustomizableEdges = borderEdges3;
            this.Logout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Logout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Logout.DisabledFillColor = System.Drawing.Color.Empty;
            this.Logout.DisabledForecolor = System.Drawing.Color.Empty;
            this.Logout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Logout.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Logout.ForeColor = System.Drawing.Color.Black;
            this.Logout.IconLeft = null;
            this.Logout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Logout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Logout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Logout.IconMarginLeft = 11;
            this.Logout.IconPadding = 10;
            this.Logout.IconRight = ((System.Drawing.Image)(resources.GetObject("Logout.IconRight")));
            this.Logout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Logout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Logout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Logout.IconSize = 25;
            this.Logout.IdleBorderColor = System.Drawing.Color.Empty;
            this.Logout.IdleBorderRadius = 0;
            this.Logout.IdleBorderThickness = 0;
            this.Logout.IdleFillColor = System.Drawing.Color.Empty;
            this.Logout.IdleIconLeftImage = null;
            this.Logout.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Logout.IdleIconRightImage")));
            this.Logout.IndicateFocus = false;
            this.Logout.Location = new System.Drawing.Point(1138, 24);
            this.Logout.Name = "Logout";
            this.Logout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Logout.OnDisabledState.BorderRadius = 0;
            this.Logout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnDisabledState.BorderThickness = 0;
            this.Logout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Logout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Logout.OnDisabledState.IconLeftImage = null;
            this.Logout.OnDisabledState.IconRightImage = null;
            this.Logout.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.onHoverState.BorderRadius = 0;
            this.Logout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.onHoverState.BorderThickness = 0;
            this.Logout.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.Logout.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Logout.onHoverState.IconLeftImage = null;
            this.Logout.onHoverState.IconRightImage = null;
            this.Logout.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.OnIdleState.BorderRadius = 0;
            this.Logout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnIdleState.BorderThickness = 0;
            this.Logout.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Logout.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Logout.OnIdleState.IconLeftImage = null;
            this.Logout.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Logout.OnIdleState.IconRightImage")));
            this.Logout.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.Logout.OnPressedState.BorderRadius = 0;
            this.Logout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Logout.OnPressedState.BorderThickness = 0;
            this.Logout.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Logout.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Logout.OnPressedState.IconLeftImage = null;
            this.Logout.OnPressedState.IconRightImage = null;
            this.Logout.Size = new System.Drawing.Size(146, 58);
            this.Logout.TabIndex = 3;
            this.Logout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Logout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Logout.TextMarginLeft = 0;
            this.Logout.TextPadding = new System.Windows.Forms.Padding(0);
            this.Logout.UseDefaultRadiusAndThickness = true;
            this.Logout.Click += new System.EventHandler(this.Logout_Click);
            // 
            // profile
            // 
            this.profile.AllowParentOverrides = false;
            this.profile.AutoEllipsis = false;
            this.profile.Cursor = System.Windows.Forms.Cursors.Default;
            this.profile.CursorType = System.Windows.Forms.Cursors.Default;
            this.profile.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.profile.Location = new System.Drawing.Point(1085, 62);
            this.profile.Name = "profile";
            this.profile.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.profile.Size = new System.Drawing.Size(29, 20);
            this.profile.TabIndex = 2;
            this.profile.Text = "Lush";
            this.profile.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.profile.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 22;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(1078, 14);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(44, 44);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 1;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(-15, -93);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(282, 282);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // Cash
            // 
            this.Cash.Controls.Add(this.tabPage1);
            this.Cash.Controls.Add(this.tabPage2);
            this.Cash.Location = new System.Drawing.Point(239, 154);
            this.Cash.Name = "Cash";
            this.Cash.SelectedIndex = 0;
            this.Cash.Size = new System.Drawing.Size(1045, 623);
            this.Cash.TabIndex = 39;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.Total_Sale);
            this.tabPage1.Controls.Add(this.bunifuLabel4);
            this.tabPage1.Controls.Add(this.data_Grid);
            this.tabPage1.Controls.Add(this.Cash_tally);
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(1037, 594);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Cash";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // data_Grid
            // 
            this.data_Grid.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.data_Grid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.data_Grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.data_Grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.data_Grid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.data_Grid.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Orange;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.data_Grid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.data_Grid.ColumnHeadersHeight = 40;
            this.data_Grid.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            this.data_Grid.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.data_Grid.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.data_Grid.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.data_Grid.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.data_Grid.CurrentTheme.BackColor = System.Drawing.Color.Orange;
            this.data_Grid.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.data_Grid.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Orange;
            this.data_Grid.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.data_Grid.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.data_Grid.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            this.data_Grid.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.data_Grid.CurrentTheme.Name = null;
            this.data_Grid.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(237)))), ((int)(((byte)(204)))));
            this.data_Grid.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.data_Grid.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.data_Grid.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.data_Grid.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(237)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.data_Grid.DefaultCellStyle = dataGridViewCellStyle3;
            this.data_Grid.EnableHeadersVisualStyles = false;
            this.data_Grid.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.data_Grid.HeaderBackColor = System.Drawing.Color.Orange;
            this.data_Grid.HeaderBgColor = System.Drawing.Color.Empty;
            this.data_Grid.HeaderForeColor = System.Drawing.Color.White;
            this.data_Grid.Location = new System.Drawing.Point(28, 147);
            this.data_Grid.Name = "data_Grid";
            this.data_Grid.RowHeadersVisible = false;
            this.data_Grid.RowHeadersWidth = 51;
            this.data_Grid.RowTemplate.Height = 40;
            this.data_Grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.data_Grid.Size = new System.Drawing.Size(983, 332);
            this.data_Grid.TabIndex = 35;
            this.data_Grid.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            // 
            // Cash_tally
            // 
            this.Cash_tally.AllowAnimations = true;
            this.Cash_tally.AllowMouseEffects = true;
            this.Cash_tally.AllowToggling = false;
            this.Cash_tally.AnimationSpeed = 200;
            this.Cash_tally.AutoGenerateColors = false;
            this.Cash_tally.AutoRoundBorders = false;
            this.Cash_tally.AutoSizeLeftIcon = true;
            this.Cash_tally.AutoSizeRightIcon = true;
            this.Cash_tally.BackColor = System.Drawing.Color.Transparent;
            this.Cash_tally.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Cash_tally.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Cash_tally.BackgroundImage")));
            this.Cash_tally.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Cash_tally.ButtonText = "Cash Tally";
            this.Cash_tally.ButtonTextMarginLeft = 0;
            this.Cash_tally.ColorContrastOnClick = 45;
            this.Cash_tally.ColorContrastOnHover = 45;
            this.Cash_tally.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Cash_tally.CustomizableEdges = borderEdges4;
            this.Cash_tally.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Cash_tally.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Cash_tally.DisabledFillColor = System.Drawing.Color.Empty;
            this.Cash_tally.DisabledForecolor = System.Drawing.Color.Empty;
            this.Cash_tally.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Cash_tally.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Cash_tally.ForeColor = System.Drawing.Color.Black;
            this.Cash_tally.IconLeft = ((System.Drawing.Image)(resources.GetObject("Cash_tally.IconLeft")));
            this.Cash_tally.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Cash_tally.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Cash_tally.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Cash_tally.IconMarginLeft = 11;
            this.Cash_tally.IconPadding = 10;
            this.Cash_tally.IconRight = null;
            this.Cash_tally.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Cash_tally.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Cash_tally.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Cash_tally.IconSize = 25;
            this.Cash_tally.IdleBorderColor = System.Drawing.Color.Empty;
            this.Cash_tally.IdleBorderRadius = 0;
            this.Cash_tally.IdleBorderThickness = 0;
            this.Cash_tally.IdleFillColor = System.Drawing.Color.Empty;
            this.Cash_tally.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Cash_tally.IdleIconLeftImage")));
            this.Cash_tally.IdleIconRightImage = null;
            this.Cash_tally.IndicateFocus = false;
            this.Cash_tally.Location = new System.Drawing.Point(402, 38);
            this.Cash_tally.Name = "Cash_tally";
            this.Cash_tally.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Cash_tally.OnDisabledState.BorderRadius = 0;
            this.Cash_tally.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Cash_tally.OnDisabledState.BorderThickness = 0;
            this.Cash_tally.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Cash_tally.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Cash_tally.OnDisabledState.IconLeftImage = null;
            this.Cash_tally.OnDisabledState.IconRightImage = null;
            this.Cash_tally.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.Cash_tally.onHoverState.BorderRadius = 0;
            this.Cash_tally.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Cash_tally.onHoverState.BorderThickness = 0;
            this.Cash_tally.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.Cash_tally.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Cash_tally.onHoverState.IconLeftImage = null;
            this.Cash_tally.onHoverState.IconRightImage = null;
            this.Cash_tally.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.Cash_tally.OnIdleState.BorderRadius = 0;
            this.Cash_tally.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Cash_tally.OnIdleState.BorderThickness = 0;
            this.Cash_tally.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Cash_tally.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Cash_tally.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Cash_tally.OnIdleState.IconLeftImage")));
            this.Cash_tally.OnIdleState.IconRightImage = null;
            this.Cash_tally.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.Cash_tally.OnPressedState.BorderRadius = 0;
            this.Cash_tally.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Cash_tally.OnPressedState.BorderThickness = 0;
            this.Cash_tally.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Cash_tally.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Cash_tally.OnPressedState.IconLeftImage = null;
            this.Cash_tally.OnPressedState.IconRightImage = null;
            this.Cash_tally.Size = new System.Drawing.Size(205, 58);
            this.Cash_tally.TabIndex = 34;
            this.Cash_tally.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Cash_tally.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Cash_tally.TextMarginLeft = 0;
            this.Cash_tally.TextPadding = new System.Windows.Forms.Padding(0);
            this.Cash_tally.UseDefaultRadiusAndThickness = true;
            this.Cash_tally.Click += new System.EventHandler(this.Cash_tally_Click);
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.FeedbackLbl);
            this.tabPage2.Controls.Add(this.Save_pass);
            this.tabPage2.Controls.Add(this.confirm_pass);
            this.tabPage2.Controls.Add(this.new_pass);
            this.tabPage2.Controls.Add(this.present_pass);
            this.tabPage2.Controls.Add(this.bunifuLabel3);
            this.tabPage2.Controls.Add(this.bunifuLabel2);
            this.tabPage2.Controls.Add(this.bunifuLabel1);
            this.tabPage2.Location = new System.Drawing.Point(4, 25);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(1037, 594);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Change Password";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // FeedbackLbl
            // 
            this.FeedbackLbl.AllowParentOverrides = false;
            this.FeedbackLbl.AutoEllipsis = false;
            this.FeedbackLbl.CursorType = null;
            this.FeedbackLbl.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FeedbackLbl.Location = new System.Drawing.Point(783, 134);
            this.FeedbackLbl.Name = "FeedbackLbl";
            this.FeedbackLbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.FeedbackLbl.Size = new System.Drawing.Size(0, 0);
            this.FeedbackLbl.TabIndex = 36;
            this.FeedbackLbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.FeedbackLbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Save_pass
            // 
            this.Save_pass.AllowAnimations = true;
            this.Save_pass.AllowMouseEffects = true;
            this.Save_pass.AllowToggling = false;
            this.Save_pass.AnimationSpeed = 200;
            this.Save_pass.AutoGenerateColors = false;
            this.Save_pass.AutoRoundBorders = false;
            this.Save_pass.AutoSizeLeftIcon = true;
            this.Save_pass.AutoSizeRightIcon = true;
            this.Save_pass.BackColor = System.Drawing.Color.Transparent;
            this.Save_pass.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Save_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save_pass.BackgroundImage")));
            this.Save_pass.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_pass.ButtonText = "Save";
            this.Save_pass.ButtonTextMarginLeft = 0;
            this.Save_pass.ColorContrastOnClick = 45;
            this.Save_pass.ColorContrastOnHover = 45;
            this.Save_pass.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Save_pass.CustomizableEdges = borderEdges5;
            this.Save_pass.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save_pass.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_pass.DisabledFillColor = System.Drawing.Color.Empty;
            this.Save_pass.DisabledForecolor = System.Drawing.Color.Empty;
            this.Save_pass.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Save_pass.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save_pass.ForeColor = System.Drawing.Color.Black;
            this.Save_pass.IconLeft = ((System.Drawing.Image)(resources.GetObject("Save_pass.IconLeft")));
            this.Save_pass.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save_pass.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save_pass.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save_pass.IconMarginLeft = 11;
            this.Save_pass.IconPadding = 10;
            this.Save_pass.IconRight = null;
            this.Save_pass.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save_pass.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save_pass.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save_pass.IconSize = 25;
            this.Save_pass.IdleBorderColor = System.Drawing.Color.Empty;
            this.Save_pass.IdleBorderRadius = 0;
            this.Save_pass.IdleBorderThickness = 0;
            this.Save_pass.IdleFillColor = System.Drawing.Color.Empty;
            this.Save_pass.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Save_pass.IdleIconLeftImage")));
            this.Save_pass.IdleIconRightImage = null;
            this.Save_pass.IndicateFocus = false;
            this.Save_pass.Location = new System.Drawing.Point(321, 288);
            this.Save_pass.Name = "Save_pass";
            this.Save_pass.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_pass.OnDisabledState.BorderRadius = 0;
            this.Save_pass.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_pass.OnDisabledState.BorderThickness = 0;
            this.Save_pass.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_pass.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_pass.OnDisabledState.IconLeftImage = null;
            this.Save_pass.OnDisabledState.IconRightImage = null;
            this.Save_pass.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.Save_pass.onHoverState.BorderRadius = 0;
            this.Save_pass.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_pass.onHoverState.BorderThickness = 0;
            this.Save_pass.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(221)))), ((int)(((byte)(131)))));
            this.Save_pass.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Save_pass.onHoverState.IconLeftImage = null;
            this.Save_pass.onHoverState.IconRightImage = null;
            this.Save_pass.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.Save_pass.OnIdleState.BorderRadius = 0;
            this.Save_pass.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_pass.OnIdleState.BorderThickness = 0;
            this.Save_pass.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Save_pass.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Save_pass.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.Save_pass.OnIdleState.IconRightImage = null;
            this.Save_pass.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.Save_pass.OnPressedState.BorderRadius = 0;
            this.Save_pass.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_pass.OnPressedState.BorderThickness = 0;
            this.Save_pass.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Save_pass.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Save_pass.OnPressedState.IconLeftImage = null;
            this.Save_pass.OnPressedState.IconRightImage = null;
            this.Save_pass.Size = new System.Drawing.Size(205, 58);
            this.Save_pass.TabIndex = 35;
            this.Save_pass.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save_pass.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save_pass.TextMarginLeft = 0;
            this.Save_pass.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save_pass.UseDefaultRadiusAndThickness = true;
            this.Save_pass.Click += new System.EventHandler(this.Save_pass_Click);
            // 
            // confirm_pass
            // 
            this.confirm_pass.AcceptsReturn = false;
            this.confirm_pass.AcceptsTab = false;
            this.confirm_pass.AnimationSpeed = 200;
            this.confirm_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.confirm_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.confirm_pass.AutoSizeHeight = true;
            this.confirm_pass.BackColor = System.Drawing.Color.Transparent;
            this.confirm_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("confirm_pass.BackgroundImage")));
            this.confirm_pass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.confirm_pass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.confirm_pass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.confirm_pass.BorderColorIdle = System.Drawing.Color.Silver;
            this.confirm_pass.BorderRadius = 1;
            this.confirm_pass.BorderThickness = 1;
            this.confirm_pass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.confirm_pass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.confirm_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.confirm_pass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.confirm_pass.DefaultText = "";
            this.confirm_pass.FillColor = System.Drawing.Color.White;
            this.confirm_pass.HideSelection = true;
            this.confirm_pass.IconLeft = null;
            this.confirm_pass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.confirm_pass.IconPadding = 10;
            this.confirm_pass.IconRight = null;
            this.confirm_pass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.confirm_pass.Lines = new string[0];
            this.confirm_pass.Location = new System.Drawing.Point(398, 196);
            this.confirm_pass.MaxLength = 32767;
            this.confirm_pass.MinimumSize = new System.Drawing.Size(1, 1);
            this.confirm_pass.Modified = false;
            this.confirm_pass.Multiline = false;
            this.confirm_pass.Name = "confirm_pass";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirm_pass.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.confirm_pass.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirm_pass.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirm_pass.OnIdleState = stateProperties4;
            this.confirm_pass.Padding = new System.Windows.Forms.Padding(3);
            this.confirm_pass.PasswordChar = '\0';
            this.confirm_pass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.confirm_pass.PlaceholderText = "Enter text";
            this.confirm_pass.ReadOnly = false;
            this.confirm_pass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.confirm_pass.SelectedText = "";
            this.confirm_pass.SelectionLength = 0;
            this.confirm_pass.SelectionStart = 0;
            this.confirm_pass.ShortcutsEnabled = true;
            this.confirm_pass.Size = new System.Drawing.Size(260, 43);
            this.confirm_pass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.confirm_pass.TabIndex = 5;
            this.confirm_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.confirm_pass.TextMarginBottom = 0;
            this.confirm_pass.TextMarginLeft = 3;
            this.confirm_pass.TextMarginTop = 1;
            this.confirm_pass.TextPlaceholder = "Enter text";
            this.confirm_pass.UseSystemPasswordChar = false;
            this.confirm_pass.WordWrap = true;
            // 
            // new_pass
            // 
            this.new_pass.AcceptsReturn = false;
            this.new_pass.AcceptsTab = false;
            this.new_pass.AnimationSpeed = 200;
            this.new_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.new_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.new_pass.AutoSizeHeight = true;
            this.new_pass.BackColor = System.Drawing.Color.Transparent;
            this.new_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("new_pass.BackgroundImage")));
            this.new_pass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.new_pass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.new_pass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.new_pass.BorderColorIdle = System.Drawing.Color.Silver;
            this.new_pass.BorderRadius = 1;
            this.new_pass.BorderThickness = 1;
            this.new_pass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.new_pass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.new_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.new_pass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.new_pass.DefaultText = "";
            this.new_pass.FillColor = System.Drawing.Color.White;
            this.new_pass.HideSelection = true;
            this.new_pass.IconLeft = null;
            this.new_pass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.new_pass.IconPadding = 10;
            this.new_pass.IconRight = null;
            this.new_pass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.new_pass.Lines = new string[0];
            this.new_pass.Location = new System.Drawing.Point(398, 144);
            this.new_pass.MaxLength = 32767;
            this.new_pass.MinimumSize = new System.Drawing.Size(1, 1);
            this.new_pass.Modified = false;
            this.new_pass.Multiline = false;
            this.new_pass.Name = "new_pass";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.new_pass.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.new_pass.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.new_pass.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.new_pass.OnIdleState = stateProperties8;
            this.new_pass.Padding = new System.Windows.Forms.Padding(3);
            this.new_pass.PasswordChar = '\0';
            this.new_pass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.new_pass.PlaceholderText = "Enter text";
            this.new_pass.ReadOnly = false;
            this.new_pass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.new_pass.SelectedText = "";
            this.new_pass.SelectionLength = 0;
            this.new_pass.SelectionStart = 0;
            this.new_pass.ShortcutsEnabled = true;
            this.new_pass.Size = new System.Drawing.Size(260, 43);
            this.new_pass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.new_pass.TabIndex = 4;
            this.new_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.new_pass.TextMarginBottom = 0;
            this.new_pass.TextMarginLeft = 3;
            this.new_pass.TextMarginTop = 1;
            this.new_pass.TextPlaceholder = "Enter text";
            this.new_pass.UseSystemPasswordChar = false;
            this.new_pass.WordWrap = true;
            // 
            // present_pass
            // 
            this.present_pass.AcceptsReturn = false;
            this.present_pass.AcceptsTab = false;
            this.present_pass.AnimationSpeed = 200;
            this.present_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.present_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.present_pass.AutoSizeHeight = true;
            this.present_pass.BackColor = System.Drawing.Color.Transparent;
            this.present_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("present_pass.BackgroundImage")));
            this.present_pass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.present_pass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.present_pass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.present_pass.BorderColorIdle = System.Drawing.Color.Silver;
            this.present_pass.BorderRadius = 1;
            this.present_pass.BorderThickness = 1;
            this.present_pass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.present_pass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.present_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.present_pass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.present_pass.DefaultText = "";
            this.present_pass.FillColor = System.Drawing.Color.White;
            this.present_pass.HideSelection = true;
            this.present_pass.IconLeft = null;
            this.present_pass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.present_pass.IconPadding = 10;
            this.present_pass.IconRight = null;
            this.present_pass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.present_pass.Lines = new string[0];
            this.present_pass.Location = new System.Drawing.Point(398, 88);
            this.present_pass.MaxLength = 32767;
            this.present_pass.MinimumSize = new System.Drawing.Size(1, 1);
            this.present_pass.Modified = false;
            this.present_pass.Multiline = false;
            this.present_pass.Name = "present_pass";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.present_pass.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.present_pass.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.present_pass.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.present_pass.OnIdleState = stateProperties12;
            this.present_pass.Padding = new System.Windows.Forms.Padding(3);
            this.present_pass.PasswordChar = '\0';
            this.present_pass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.present_pass.PlaceholderText = "Enter text";
            this.present_pass.ReadOnly = false;
            this.present_pass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.present_pass.SelectedText = "";
            this.present_pass.SelectionLength = 0;
            this.present_pass.SelectionStart = 0;
            this.present_pass.ShortcutsEnabled = true;
            this.present_pass.Size = new System.Drawing.Size(260, 43);
            this.present_pass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.present_pass.TabIndex = 3;
            this.present_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.present_pass.TextMarginBottom = 0;
            this.present_pass.TextMarginLeft = 3;
            this.present_pass.TextMarginTop = 1;
            this.present_pass.TextPlaceholder = "Enter text";
            this.present_pass.UseSystemPasswordChar = false;
            this.present_pass.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(234, 207);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(119, 20);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Confirm Password";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(234, 155);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(96, 20);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "New Password";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(234, 100);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(114, 20);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Present Password";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(720, 520);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(66, 20);
            this.bunifuLabel4.TabIndex = 36;
            this.bunifuLabel4.Text = "Total Sale";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Total_Sale
            // 
            this.Total_Sale.AllowParentOverrides = false;
            this.Total_Sale.AutoEllipsis = false;
            this.Total_Sale.Cursor = System.Windows.Forms.Cursors.Default;
            this.Total_Sale.CursorType = System.Windows.Forms.Cursors.Default;
            this.Total_Sale.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Total_Sale.Location = new System.Drawing.Point(852, 520);
            this.Total_Sale.Name = "Total_Sale";
            this.Total_Sale.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Total_Sale.Size = new System.Drawing.Size(0, 0);
            this.Total_Sale.TabIndex = 37;
            this.Total_Sale.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Total_Sale.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // user_options
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1300, 800);
            this.Controls.Add(this.Cash);
            this.Controls.Add(this.bunifuGradientPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "user_options";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "user_options";
            this.bunifuGradientPanel2.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.Cash.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.data_Grid)).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton optionsBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton receptionbtn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Logout;
        private Bunifu.UI.WinForms.BunifuLabel profile;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.TabControl Cash;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Cash_tally;
        private Bunifu.UI.WinForms.BunifuDataGridView data_Grid;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Save_pass;
        private Bunifu.UI.WinForms.BunifuTextBox confirm_pass;
        private Bunifu.UI.WinForms.BunifuTextBox new_pass;
        private Bunifu.UI.WinForms.BunifuTextBox present_pass;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel FeedbackLbl;
        private Bunifu.UI.WinForms.BunifuLabel Total_Sale;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
    }
}